---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation

FILTER_REGEX_EXCLUDE: '(fonts)'
APPLY_FIXES: all
DISABLE_LINTERS:
  - JSON_PRETTIER
  - YAML_PRETTIER
  - COPYPASTE_JSCPD
  - REPOSITORY_DEVSKIM 
EMAIL_REPORTER: false
SPELL_FILTER_REGEX_EXCLUDE: (fonts|\.github|.mega-linter.yml)
LATEX_CHKTEX_ARGUMENTS: --nowarn 13

TERRAFORM_KICS_ARGUMENTS: --fail-on "critical,high,medium"
